import dataclasses
from enum import Enum

class MediaTypeEnum(str, Enum):
    IMAGE_PROFILE_PICTURE = "IMAGE_PROFILE_PICTURE"
    IMAGE_DRIVERS_LICENSE_FRONT = "IMAGE_DRIVERS_LICENSE_FRONT"
    IMAGE_DRIVERS_LICENSE_BACK = "IMAGE_DRIVERS_LICENSE_BACK"
    IMAGE_PASSPORT_FRONT = "IMAGE_PASSPORT_FRONT"
    IMAGE_ID_CARD_FRONT = "IMAGE_ID_CARD_FRONT"
    IMAGE_ID_CARD_BACK = "IMAGE_ID_CARD_BACK"
    IMAGE_FACE_IMAGE = "IMAGE_FACE_IMAGE"
